// <auto-generated />
using System;
using BookingTelegramBot.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingTelegramBot.DAL.Migrations
{
    [DbContext(typeof(BookingRoomDbContext))]
    [Migration("20200211131315_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookingTelegramBot.Repository.Models.Parameter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Board")
                        .HasColumnType("bit");

                    b.Property<bool>("Camera")
                        .HasColumnType("bit");

                    b.Property<bool>("Computer")
                        .HasColumnType("bit");

                    b.Property<int>("CountOfChairs")
                        .HasColumnType("int");

                    b.Property<int>("CountOfTable")
                        .HasColumnType("int");

                    b.Property<bool>("Display")
                        .HasColumnType("bit");

                    b.Property<bool>("Microphone")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfPersons")
                        .HasColumnType("int");

                    b.Property<bool>("Phone")
                        .HasColumnType("bit");

                    b.Property<bool>("Projector")
                        .HasColumnType("bit");

                    b.Property<bool>("ProjectorControlPanel")
                        .HasColumnType("bit");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RoomId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("BookingTelegramBot.Repository.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("BookingTelegramBot.Repository.Models.UserReservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeTo")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("RoomId");

                    b.ToTable("UsersReservations");
                });

            modelBuilder.Entity("BookingTelegramBot.Repository.Models.Parameter", b =>
                {
                    b.HasOne("BookingTelegramBot.Repository.Models.Room", "Room")
                        .WithMany("Parameters")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("BookingTelegramBot.Repository.Models.UserReservation", b =>
                {
                    b.HasOne("BookingTelegramBot.Repository.Models.Room", "Room")
                        .WithMany("UsersReservations")
                        .HasForeignKey("RoomId");
                });
#pragma warning restore 612, 618
        }
    }
}
